#pragma once

void procrastinationAscii();
void phoneAscii();
void classroomAscii();
void testAscii();
void titleAscii();
void groupassignmentAscii();
void homeAscii();
void apuAscii();
void klccAscii();
void libraryAscii();
void cafeAscii();
void shopAscii();
void cinemaAscii();
void elevatorAscii();
void seniorAscii();
void moneyAscii();
void activityAscii();
void storeAscii();
void streetAscii();
void bagAscii();
void lostAscii();
void classmateAscii();
void gamingAscii();
void classmatesAscii();
void finalexamAscii();