#pragma once

void procrastination();
void phone();
void classroom();
void test();
void title();
void groupassignment();
void home();
void apu();
void klcc();
void library();
void cafe();
void shop();
void cinema();
void elevator();
void senior();
void money();
void activity();
void store();
void street();
void bag();
void lost();
void classmate();